name: rexsys
author: rexjohannes98
version: 1.0
main: de.pattyxdhd.feed.FeedPlugin

commands:
  feed:
  fly:
  heal:
  gm:
    aliases:
      - gamemode
  invsee:
  msg:
  tp:
  top:
  rtp:
  kick:
  mutechat:
  mutep:
  sudo:
  ping:
  rename:
  slowchat:
  rex:
  clearchat:
    aliases:
      - cc
  enderchest:
    aliases:
      - ec
  generate:
  vanish:
  feuerwerk: